import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import ApolloClientProvider from "@/components/ApolloClientProvider";
import AuthProvider from "@/components/Authprovider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          {/* ApolloProvider is now safely inside a Client Component */}
          <ApolloClientProvider>{children}</ApolloClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
